### ISSUE TITLE
Laravel-Admin:install

### ISSUE THREAD

**Issue by karneaud** [sohelamin/laravel-starter#3]
Was successful in installing the starter but when trying to run `php artisan laravel-admin:install` gives me

> [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "laravel-admin" namespace.

Would there be another step to do? What about the CRUD generator?

**Comment by sohelamin** [comment]
The command you've mentioned is for https://github.com/appzcoder/laravel-admin

This is just a boilerplate app with Vue.js

**Comment by karneaud** [comment]
My apologies I assumed they were one in the same
