### ISSUE TITLE
Change login redirect to Admin

### ISSUE THREAD

**Issue by randycasburn** [sohelamin/laravel-starter#7]
Please consider changing:

`    protected $redirectTo = '/home';
`
to
`    protected $redirectTo = '/admin';
`
in app/Http/Controllers/Auth/LoginController.php

Thanks.

**Comment by sohelamin** [comment]
Hi @randycasburn 

Did you see?
```
    protected function authenticated(Request $request, $user)
    {
        if ($user->hasRole('admin')) {
            return redirect('/admin');
        }

        return redirect('home');
    }
```

If the user has admin role then it will be automatically redirected to admin route.

**Comment by randycasburn** [comment]
I suppose I missed that work flow. I'll close this.
